kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = 192.168.6.147
    http_port = 3000
    root_url = https://%(domain)s/api/grafana/
    serve_from_sub_path = true
    [security]
    allow_embedding = true
    [auth.generic_oauth]
    name = OAuth
    enabled = true
    allow_sign_up = true
    client_id = grafana2
    client_secret = 514512a6-b562-4058-9cb0-ce3faefb9e81
    scopes = openid profile email
    email_attribute_name = email:primary
    email_attribute_path = email
    role_attribute_path = 
    auth_url = https://hyperauth.org/auth/realms/tmax/protocol/openid-connect/auth
    token_url = https://hyperauth.org/auth/realms/tmax/protocol/openid-connect/token
    api_url = https://hyperauth.org/auth/realms/tmax/protocol/openid-connect/userinfo
    allowed_domains = 
    team_ids =
    allowed_organizations =
    send_client_credentials_via_post = false
    tls_skip_verify_insecure = false
    [auth.anonymous]
    enabled = true
    [users]
    default_theme = light

