kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [security]
    allow_embedding = true
    [auth.anonymous]
    enabled = true
    [server]
    domain = example.com
    root_url = %(protocol)s://%(domain)s:%(http_port)s/api/grafana/
    serve_from_sub_path = true
    [users]
    default_theme = light
