apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
  labels:
    app: grafana
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {GRAFANA_PVC}
