apiVersion: v1
kind: Secret
metadata:
  name: selfsigned-ca
  namespace: monitoring
type: Opaque
stringData:
  # api-gateway-system 네임스페이스의 selfsigned-crt-secret에 있는 ca.crt를 아래의 형식에 맞추어 붙여넣기(띄어쓰기 포함)
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDFDCCAfygAwIBAgIRAMv5gYRn62NbTeGZTUjw7sswDQYJKoZIhvcNAQELBQAw
    
    
    
    
    ...
    
    
    
    
    
    R8mmeoP6Xz6IQFTwkGXaKuP11txXLFjx
    -----END CERTIFICATE-----
